CREATE TABLE ALUNOS
	ID SERIAL PRIMRARY KEY
	RA VHARCHAR NOT NULL
	NOME
	DATACADASTRO DATE
	EMAIL VARCHAR
	TELEFONE VARCHAR
	ENDERECO VARCHAR
	INICIOCURSO DATE
	CONCLUSAOCURSO DATE
	STATUS VARCHAR (1, 1) NOT NULL